project: 
  type: website
  
website: 
  page-navigation: true
  title: "Making sharable documents with Quarto" 
  site-url: "https://mariabartlett.github.io/massive-data-spring-2025-final-project/" 
  repo-url: https://github.com/mariabartlett/massive-data-spring-2025-final-project
    
  sidebar:
    tools: 
      - icon: github
        href: https://github.com/mariabartlett/massive-data-spring-2025-final-project
        text: "View GitHub repository"        

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - quarto

  
