project: 
  type: website
  render:
    - index.qmd
    - policy-context.qmd
    - data-source.qmd
    - data-pipeline.qmd
    - analyses.qmd
    - institution-reports.qmd
    - references.qmd
  
website: 
  page-navigation: true
  site-url: "https://mariabartlett.github.io/massive-data-spring-2025-final-project/" 
  repo-url: https://github.com/mariabartlett/massive-data-spring-2025-final-project
  repo-actions: [source]

  page-footer:
    right: "Data Science for Public Policy @ Georgetown University"
    left: "Bridgette Sullivan, Jasmine Jia, Katharyn Loweth, & Maria Bartlett"
  
  sidebar:      
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Project background & site overview
      - href: policy-context.qmd
        text: Policy context
      - href: data-source.qmd
        text: RQs & data source
      - href: data-pipeline.qmd
        text: Data pipeline
      - href: analyses.qmd
        text: Analytics
      - href: institution-reports.qmd
        text: Institution reports
      - href: references.qmd
        text: References

format:
  html:
    theme: lux
    code-copy: true
    code-overflow: wrap
    toc: true