project: 
  type: website
  render:
    - index.qmd
  
website: 
  page-navigation: true
  title: "Designing a data pipeline to analyze gender equity in college sports" 
  site-url: "https://mariabartlett.github.io/massive-data-spring-2025-final-project/" 
  repo-url: https://github.com/mariabartlett/massive-data-spring-2025-final-project

  page-footer:
    right: "2025 PPOL 5206 final project"
    left: "Bridgette Sullivan, Jasmine Jia, Katharyn Loweth, & Maria Bartlett"
    
  sidebar:
    tools: 
      - icon: github
        href: https://github.com/mariabartlett/massive-data-spring-2025-final-project
        text: "View GitHub repository"        

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Project background & policy context
      - href: data-pipeline.qmd
        text: Data pipeline
      - href: analyses.qmd
        text: Analytics
      - href: Institutional reports
        text: institution-reports.qmd

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true