---
title: "Designing a data pipeline to analyze gender equity in college sports"
subtitle: "Spring 2025 Massive Data Fundamentals final project"
title-block-banner: track-image.jpg
include-in-header:
  - text: |
      <style>
      .quarto-title-block .quarto-title-banner {
        background-position-y: right;
        height: 200px;
        text-align: left;
      }
      .title {
        color: black;
        font-weight: bold
      }
      .subtitle {
        color: black
      }
      </style>
---

# Policy context

Gender disparities persist as a complex challenge in the United States, where equal opportunity is a core national value. During the civil rights movement of the 1960s and 1970s, Congress enacted legislation that made sex-based discrimination illegal in certain environments (NWLC, 2022a). Specifically in 1972, Congress passed Title IX, which prohibits sex-based discrimination in educational institutions that receive federal funding (NWLC, 2022a). Title IX not only protects students from sexual harassment and discrimination but also mandates that schools allocate athletic participation opportunities in a nondiscriminatory way (NWLC, 2022b; Casciani, 2021). 

Over the last fifty years, Congress and the Department of Education have continued to update the guidance and protocols for Title IX to better monitor its compliance (Office of Civil Rights, n.d.). In 1979, the Department of Education established that an individual institution’s intercollegiate athletics program must fulfill one of three defined criteria to be recognized as compliant: 

1) The number of male and female athletes is in proportion to the institution’s respective student enrollment counts

2) The institution currently expands and has historically expanded participation opportunities “demonstrably responsive to the developing interest and abilities” of the underrepresented sex  (Office of Civil Rights, n.d.)

3) If expansion of opportunities for the underrepresented sex has not been apparent, “the interests and abilities of the members of that sex have been fully and effectively accommodated by the present program” (Office of Civil Rights, n.d.).

Several years later, Congress enacted the Equity in Athletics Disclosure Act (EADA) in 1994 to make it easier to track Title IX compliance in higher education institutions' athletic programs (NCAA, n.d.; NWLC, n.d.). The EADA requires colleges and universities that (1) receive federal financial assistance (Title IV Federal Student Aid) and (2) sponsor intercollegiate athletics to report data annually on male and female athletics participation, staffing and other resources for the male and female athletic teams, and the revenues and expenses for the male and female athletic teams to the Department of Education (NCAA, n.d.). The data is then made publicly available by the institution and by the Department of Education (NCAA, n.d.; GAO, 2024). 

Because of the EADA, we know that the gender gap in sports continues to exist within higher education institutions. The U.S. Government Accountability Office reported that during the 2021-2022 academic year, the overall athletic participation rate for women (42%) was 14 percentage points lower than their enrollment rate (56%) (GAO, 2024). In contrast, the athletic participation rate for men (58%) was 14 percentage points higher than their enrollment rate (44%) (GAO, 2024). Additionally, nearly half of colleges (40%) have not increased the number of varsity sports available to women since the 2009–2010 academic year (GAO, 2024). 
